models = {
    "sdxl-base-v10-vaefix": {},
    "tempest-by-vlad-0.1": {},
    "icbinpXL_v6": {},
    "PrometheusV1": {},
    "Epicrealismxl_Hades": {},
    "juggernautXL_juggXIByRundiffusion": {},
    "juggernautXL_ragnarokBy": {},
    "AnythingXL_xl": {},
    "dreamshaperXL_alpha2Xl10": {},
    "perfectdeliberate_XL": {},
    "stabilityai/stable-diffusion-3.5-medium": {},
    "stabilityai/stable-diffusion-3.5-large": {},
    "stabilityai/stable-cascade": {},
    "black-forest-labs/FLUX.1-dev": {},
    "black-forest-labs/FLUX.1-Kontext-dev": {},
    "black-forest-labs/FLUX.1-Krea-dev": {},
    "lodestones/Chroma1-HD": {},
    "vladmandic/chroma-unlocked-v50-annealed": {},
    "vladmandic/chroma-unlocked-v48": {},
    "vladmandic/chroma-unlocked-v48-detail-calibrated": {},
    "ostris/Flex.2-preview": {},
    "ostris/Flex.1-alpha": {},
    "Qwen/Qwen-Image": {},
    "vladmandic/Qwen-Lightning": {},
    "Efficient-Large-Model/SANA1.5_1.6B_1024px_diffusers": {},
    "Efficient-Large-Model/SANA1.5_4.8B_1024px_diffusers": {},
    "zai-org/CogView4-6B": {},
    "zai-org/CogView3-Plus-3B": {},
    "fal/AuraFlow-v0.3": {},
    "fal/AuraFlow-v0.2": {},
    "Freepik/F-Lite": {},
    "Freepik/F-Lite-Texture": {},
    "Freepik/F-Lite-7B": {},
    "playgroundai/playground-v2-1024px-aesthetic": {},
    "playground-v2.5-1024px-aesthetic.fp16": { "sampler_name": "DPM++ 2M EDM" },
    "Shitao/OmniGen-v1-diffusers": {},
    "OmniGen2/OmniGen2": {},
    "kandinsky-community/kandinsky-2-2-decoder": {},
    "kandinsky-community/kandinsky-2-1": {},
    "kandinsky-community/kandinsky-3": {}, # corrupt output
    "Alpha-VLLM/Lumina-Next-SFT-diffusers": {},
    "Alpha-VLLM/Lumina-Image-2.0": {},
    "PixArt-alpha/PixArt-XL-2-1024-MS": {},
    "PixArt-alpha/PixArt-Sigma-XL-2-1024-MS": {},
    "nvidia/Cosmos-Predict2-2B-Text2Image": {},
    "nvidia/Cosmos-Predict2-14B-Text2Image": {},
    "Wan-AI/Wan2.1-T2V-1.3B-Diffusers": {},
    "Wan-AI/Wan2.1-T2V-14B-Diffusers": {},
    "Wan-AI/Wan2.2-TI2V-5B-Diffusers": {},
    "MeissonFlow/Meissonic": {},
    "briaai/BRIA-3.2": {},
    "segmind/Segmind-Vega": {},
    "Kwai-Kolors/Kolors-diffusers": {},
    # requires fp16
    "Tencent-Hunyuan/HunyuanDiT-v1.2-Diffusers": {},
    "Tencent-Hunyuan/HunyuanDiT-v1.2-Diffusers-Distilled": {},
    "Tencent-Hunyuan/HunyuanDiT-v1.1-Diffusers": {},
    "Tencent-Hunyuan/HunyuanDiT-v1.1-Diffusers-Distilled": {},
    # requires uint4
    # "Wan-AI/Wan2.2-T2V-A14B-Diffusers": {}, # extreme memory usage due to size
    # "HiDream-ai/HiDream-I1-Full": {}, # extreme memory usage due to size
}

styles = {
    "404 sign": "Old rusty '404' road sign, postapocalypse, destroyed highway, full of debris and car wrecks leading into canyon, intricate details, volumetric lighting",
    "SD.Next logo": "'*SDNext*' text logo with abstract painted background",
    "SD.Next neon": "Large neon sign with text 'SDNext', futuristic sci-fi city, high detailed",
    "Cute robot": "photo of a cute blue robot with glowing glyph on a chest plate next to a road sign, next to a spaceship, walking sand with battle visible in background, rich details, 4k",
    "Large robot": "Large robot with a humanoid head, predominantly blue and white, standing on its hind legs, arms outstretched as if in surprise, intricate mechanical parts visible on the body, glowing red eyes, detailed armor plating on its head, arm has visible joints and joint",
    "Android robot": "Photo of female android robot in white battle armor and with blonde face standing on a surface of a rocky planet with large moon visible in the background. pitch black night with stars visible. volumetric lighting, sharp shadows. boots with high heels.",
    "Still life": "A still life photograph of an antique table, large beautiful red and purple poppy blossom in a crystal vase, loose oranges and watermelon cut in half on a porcelain plate, background black, dramatic lighting",
    "Astronaut in diner": "Photo of an astronaut eating fries at a diner, with a milkshake and burger at the table, god rays, dark helmet glass, cant see his face, cinematic, analog film, cold color palette",
    "Bear catching fish": "Photo of bear catching a fish, intricate details, sunrise, high details, inspirational, national geographics",
    "Hypercar": "Photo of a futuristic hyper car on a race track, motion blur",
    "Oil canvas": "Oil canvas painting of a young woman drawing in a very clean and well organized contemporary place, wearing hair ribbon, god rays are shining through the windows creating high contrast",
    "Lady from Fallout": "Photo of a beautiful woman, wearing tight dress and boots, looking at camera and with a dog next to her, walking through postapocalyptic steampunk city, exploration, cinematic, realistic, hyper detailed, photorealistic maximum detail, volumetric light, focus, wide-angle",
    "Lady in rain": "Scene from sin city, photorealistic wet sexy young woman holding umbrella and walking in the city square, long hair, transparent wet shirt, mini skirt, buildings with neon signs, during night, visible raindrops falling, reflections on the floor, perfect face, extreme detailed, dslr, leika",
    "Lady in Tokyo": "Photo of a young woman with steel eyes, makeup and lipstick is posing in a futuristic cyberpunk style tokyo street. ground is wet with large puddles. her very long hair is flowing in the wind. she is wearing a torn tight transparent lace dress and high heel boots. light is coming from street lamps and behind windows and casting strong shadows. building has a neon sign with text 'sdnext'. full moon is rising in the background",
    "Lady in bedroom": "Woman sitting in darkness with morning light moving over her body, kneeling on a bed, smooth skin in moody lighting, long blonde hair and perfect body, rule of thirds, perfect composition, inspirational, amazingly realistic render in 4k",
    "Lady in lace": "Beautiful seductive woman wearing glasses, lipstick, freckles, necklace, open shirt, bare shoulders, short jacket, short skirt, lace bra and stockings, high heels, tanlines, volumetric lighting, floor reflection, shot on canon 5d, instagram post",
    "Lady in gown": "A striking seductive maid in a timeless gown with shimmering fabric, her face lit up by soft golden light casting dramatic shadows across a velvet-laced room filled with elegant furniture and candlelight. The air hums with intrigue, blending sensual allure with refined elegance",
    "Mad max selfie": "Mad max movie sexy young woman character in dynamic poses, wide angle selfie style shot inside a vehicle, intricate, hyper-detailed, magic atmosphere, vibrant colors, hyper-realistic, detailed facial features, glowing colors, cinestill 50d",
    "Party yacht": "Bronze megayacht in Adriatic sea during sunset with group of women wearing colorful string bikinis and having a party on the deck",
    "Pirate ship in space": "Pirate ship trapped in a cosmic maelstrom nebula rendered in cosmic beach whirlpool engine. volumetric lighting, spectacular, ambient lights, light pollution, cinematic atmosphere, art nouveau style, illustration art artwork by SenseiJaye, intricate detail",
    "Nier Automata": "3D render of Nier Automata 2b wearing intricate costume, high details, 4k, sun rays",
    "Yoga studio": "Beautiful women practicing yoga, sweaty skin, volumetric light, in a dance studio",
    "Anime render": "Highly detailed 3D render, Anime style, female figure approximately 25 years old, slender build with pale skin and delicate facial features. She wears a flowing white silk kimono partially open revealing her torso; intricate embroidery depicting cherry blossoms in shades of pink and gold adorns the fabric",
    "Anime detailed": "A breathtakingly rendered, highly detailed anime scene featuring a stunningly beautiful woman. She’s draped across a weathered wooden porch of a sprawling, slightly dilapidated farmhouse – think exposed beams, overgrown vines, and faded floral wallpaper. Her features are exquisitely sculpted, showcasing smooth skin and perfectly defined curves. Shes adorned with flowing, crimson silk robes embroidered with intricate tribal patterns, catching the faint moonlight filtering through gaps in the roof. The lighting is deliberately dim, creating dramatic shadows and highlighting the texture of her skin and the rough wood around her. A scattering of wildflowers—pale blues and purples—dances near her feet",
    "Steampunk detailed": "Young woman, late twenties, slender build, possesses strikingly silver hair woven into tight braids threaded with polished brass gears – miniature clockwork butterflies fluttering within; wears a custom-made Victorian-era uniform of deep indigo velvet overlaid with copper piping detailing, accented with glowing emerald green crystals embedded in the lapel and cuffs; reveals subtly angled, oversized goggles crafted from blackened steel reflecting the nascent sunrise; her expression is serene yet slightly melancholic, captured in a wide-angle, handheld selfie mode—a single, perfectly framed lens focuses on her face as golden light spills over a rain-slicked cityscape constructed of towering gothic spires and colossal, steam-powered automatons frozen mid-motion; the air hangs thick with ozone and the scent of aged parchment and lubricating oil;  the backdrop consists of fragmented holographic advertisements for arcane technologies - swirling nebulae rendered in iridescent blues and oranges, partially obscured by dense fog illuminated by flickering gas lamps; a palpable sense of forgotten grandeur permeates the scene, imbued with subtle magical distortions suggesting echoes of past events – a lone, ornate fountain cascades silently down a moss-covered wall, its surface shimmering with trapped starlight.  Overall mood: ethereal melancholy, bordering on wonderstruck awe. Aesthetic Style: Neo-Victorian Industrial Gothic, saturated with bioluminescent flora growing along the edges of buildings.",
    "Steampunk hummingbird": "Time travelers in steampunk suits riding mechanical hummingbirds through shattered timelines",
    "Steampunk city": "Steampunk city, exploration, cinematic, realistic, hyper detailed, photorealistic maximum detail. volumetric light, focus, wide-angle, during night",
    "Cyberpunk city": "Cyberpunk city, exploration, cinematic, realistic, hyper detailed, photorealistic maximum detail. volumetric light, focus, wide-angle, during night",
    "Postapocalyptic city": "Postapocalyptic large city ruins, exploration, cinematic, realistic, hyper detailed, photorealistic maximum detail, volumetric light, focus, wide-angle, brightly lit, lightning",
    "Fantasy city": "fantasy city landscape with a river flowing through it, high detailed, night scene",
}
