models = {
    "sdxl-base-v10-vaefix": {},
    "tempest-by-vlad-0.1": {},
    "icbinpXL_v6": {},
    "pony-diffusion_v6": {},
}
models_all = {
    "sdxl-base-v10-vaefix": {},
    "tempest-by-vlad-0.1": {},
    "icbinpXL_v6": {},
    "pony-diffusion_v6": {},
    "briaai/BRIA-3.2": {},
    "Freepik/F-Lite": {},
    "Freepik/F-Lite-Texture": {},
    "ostris/Flex.2-preview": {},
    "playgroundai/playground-v2-1024px-aesthetic": {},
    "playground-v2.5-1024px-aesthetic.fp16": { "sampler_name": "DPM++ 2M EDM" },
    "stabilityai/stable-diffusion-3.5-medium": {},
    "stabilityai/stable-diffusion-3.5-large": {},
    "fal/AuraFlow-v0.3": {},
    "fal/AuraFlow-v0.2": {},
    "zai-org/CogView4-6B": {},
    "zai-org/CogView3-Plus-3B": {},
    "Qwen/Qwen-Image": {},
    "vladmandic/Qwen-Lightning": {},
    "Shitao/OmniGen-v1-diffusers": {},
    "OmniGen2/OmniGen2": {},
    "Kwai-Kolors/Kolors-diffusers": {},
    "kandinsky-community/kandinsky-2-2-decoder": {},
    "kandinsky-community/kandinsky-2-1": {},
    "kandinsky-community/kandinsky-3": {}, # corrupt output
    "Alpha-VLLM/Lumina-Next-SFT-diffusers": {},
    "Alpha-VLLM/Lumina-Image-2.0": {},
    "MeissonFlow/Meissonic": {},
    "Efficient-Large-Model/SANA1.5_1.6B_1024px_diffusers": {},
    "Efficient-Large-Model/SANA1.5_4.8B_1024px_diffusers": {},
    "PixArt-alpha/PixArt-XL-2-1024-MS": {},
    "PixArt-alpha/PixArt-Sigma-XL-2-1024-MS": {},
    "stabilityai/stable-cascade": {},
    "nvidia/Cosmos-Predict2-2B-Text2Image": {},
    "nvidia/Cosmos-Predict2-14B-Text2Image": {},
    "black-forest-labs/FLUX.1-dev": {},
    "black-forest-labs/FLUX.1-Kontext-dev": {},
    "black-forest-labs/FLUX.1-Krea-dev": {},
    "lodestones/Chroma1-HD": {},
    "vladmandic/chroma-unlocked-v50-annealed": {},
    "vladmandic/chroma-unlocked-v48": {},
    "vladmandic/chroma-unlocked-v48-detail-calibrated": {},
    "Wan-AI/Wan2.1-T2V-1.3B-Diffusers": {},
    "Wan-AI/Wan2.1-T2V-14B-Diffusers": {},
    "Wan-AI/Wan2.2-TI2V-5B-Diffusers": {},
    "Tencent-Hunyuan/HunyuanDiT-v1.2-Diffusers": {},
    "Tencent-Hunyuan/HunyuanDiT-v1.1-Diffusers": {},
    # "HiDream-ai/HiDream-I1-Full": {}, # extreme memory usage due to size
    # "Wan-AI/Wan2.2-T2V-A14B-Diffusers": {}, # extreme memory usage due to size
}
styles = [
    'Fixed Astronaut',
    'Fixed Bear',
    'Fixed Steampunk City',
    'Fixed SDNext Neon',
    'Fixed Road sign',
    'Fixed Astronaut',
]
styles_all = [
    'Fixed Steampunk City',
    'Fixed Futuristic hypercar',
    'Fixed Pirate Ship in Space',
    'Fixed Bear',
    'Fixed Fallout girl',
    'Fixed Kneeling on Bed',
    'Fixed Girl in Sin City',
    'Fixed Girl in a city',
    'Fixed Girl in Lace',
    'Fixed Lady in Tokyo',
    'Fixed MadMax selfie',
    'Fixed Party Yacht',
    'Fixed Yoga Girls',
]
